### ISSUE TITLE
deprecated autowiring

### ISSUE THREAD

**Issue by wladimiravila** [mcfedr/awspushbundle#24]
Hi, Im  using symfony 3.4.22  and apear this deprecated

Autowiring services based on the  types they implement is deprecated since Symfony 3.3 and won't be  supported in version 4.0. You should rename (or alias) the "mcfedr_aws_push.sns_client" service to "Aws\Sns\SnsClient" instead.

my composer has this detail information 

            "name": "mcfedr/awspushbundle",
            "version": "6.11.0",
            "source": {
                "type": "git",
                "url": "https://github.com/mcfedr/awspushbundle.git",
                "reference": "8a90e38b8f463e86618be816553f35e9262ad0dc"
            },

could I can remove this deprecated?

**Comment by mcfedr** [comment]
I suspect you are using `Aws\Sns\SnsClient` somewhere and autowiring it.

The client created by the bundle is meant for internal use - i purposefully dont call it `Aws\Sns\SnsClient` as you might want to create your own client and this would then conflict with it.

I suggest you add your own client to your services.yaml, something like:

```yaml
Aws\Sns\SnsClient:
        arguments:
          -
            version: "2010-03-31"
            region: "%region%"
            credentials: "%creds%"
```
